### ISSUE TITLE
Getting extra request data from Plug

### ISSUE THREAD

**Issue by mikebaldry** [elixir-addicts/rollbax#35]
Hi,

Just thought I'd post something I'm using to get request data from Plug to make Rollbax more useful when identifying issues.

Could be something good to refine and include in this package.

```elixir
defp handle_errors(conn, %{kind: kind, reason: reason, stack: stack}) do
    conn =
      conn
      |> Plug.Conn.fetch_cookies
      |> Plug.Conn.fetch_query_params
      |> Plug.Conn.fetch_session

    remote_ip =
      conn.remote_ip
      |> Tuple.to_list
      |> Enum.join(".")

    headers =
      conn.req_headers
      |> Enum.into(%{})

    conn_data = %{
      "request" => %{
        "cookies" => conn.req_cookies,
        "url" => "#{conn.scheme}://#{conn.host}:#{conn.port}#{conn.request_path}",
        "user_ip" => remote_ip,
        "headers" => headers,
        "session" => conn.private[:plug_session] || %{},
        "params" => conn.params,
        "method" => conn.method,
        "request_id" => UUID.uuid1,
      },
      "server" => %{
        "pid" => System.get_env("DYNO"),
        "host" => "#{System.get_env("HEROKU_APP_NAME")}:#{System.get_env("PORT")}",
        "root" => System.get_env("HOME")
      }
    }

    Rollbax.report(kind, reason, stack, %{}, conn_data)
  end
```

**Comment by whatyouhide** [comment]
Hey @mikebaldry, thanks for taking the time for this, really appreciate it. Since Rollbax has no relation whatsoever with Plug (except both being Elixir libraries 😄), I'm definitely 👎 on adding anything like this *to the library*.

However, this is really really valuable code that many people could benefit from; my suggestion is to add this to Rollbax in the form of documentation. For example, we accepted https://github.com/elixir-addicts/rollbax/pull/17 that added a Plug/Phoenix example to the README, so we're definitely open to that. In that spirit, if you want you can contribute a PR that adds a page in the documentation (see `mix help docs` for info about ex_doc pages) that describes this use case: e.g., something like "Using Rollbax in Plug-based applications". If you don't want to open a PR, no worries, I can take care of it :). Wdyt?

**Comment by mikebaldry** [comment]
I understand - it could be a complementary package rollbax-plug which adds the this method on top.. save people copy pasting code from documentation which I think is bad practice.

**Comment by whatyouhide** [comment]
@mikebaldry yes, it could be a `rollbax_plug` package of course. I am not against having this in the documentation because it's not "copy-pasting" from the documentation, it's implementing the solution *you* need with the help of the documentation (e.g., I may not want to bring all those metadata in my reports or similar problems).

**Comment by mikebaldry** [comment]
Its a very common solution though - I'm sure the majority of people who use Rollbar in a web app will be using plug and will want to tell Rollbar all the web specific paramters it accepts so the UI gives them more details when an error does happen.

**Comment by whatyouhide** [comment]
The idea you showed could be a very common solution, definitely, but the implementation I'm not sure: it makes a lot of assumptions, such as fetching the cookies/query params/session, reading stuff from environment variables, and so on. What if I want this in my code, but I want to filter headers because there are sensitive data in theme for example? This is the point I was trying to make :)

**Comment by mikebaldry** [comment]
Yeah, some of it more specific to my use case. things like cookies/query/session is what you'd always want to see? exactly what plug sees. The package could provide configuration for filtering sensitive fields/headers possibly.

**Comment by whatyouhide** [comment]
I'm not sure there's anything I'd *always* like to see: everything depends on the use case.

Yes, if you go with the package way then the package could provide very granular configuration on what to send and what not to send; you can give it a try and see how it looks. My instinct tells me that to provide really granular configuration would require a lot of work that I'm not sure would be worth considering the snippet of code in this issue is pretty small and people could adapt it to their needs very easily. But again, you can of course give the separate library a try and see how it goes :)

**Comment by mikebaldry** [comment]
:+1: I just know the Rollbar gem for Ruby, which I'm familiar with doesn't really have any options, I think it scrubs some fields by default, but other than that, you just let it do its job and you do yours and everyone is happy.

**Comment by whatyouhide** [comment]
Hey @mikebaldry, I added a [page to the documentation]() in f4be17d712b8888c3d13ab08be50ffc630f84102 that has basically your example in it as I talked about earlier. Let me know how it looks, you're of course still free to create a separate library if you feel there's the need for it. Closing this for now 💟 

(btw quick digression, yep that's the Ruby way, you just plug and it works, then you have to change something, and you see the depth of hell 😄 I say less magic, more explicitness! 💪)
