### ISSUE TITLE
Ignore Routing errors 

### ISSUE THREAD

**Issue by noma4i** [elixir-addicts/rollbax#45]
Any possible way to set a list of error to skip?

**Comment by whatyouhide** [comment]
@noma4i with Rollbax you either specifically report an error via `Rollbax.report/3-5` or you report errors via the `Rollbax.Logger` Logger backend. In the first case, you specifically report errors so you can choose which errors not to report. Are you talking about the second case?

**Comment by noma4i** [comment]
Im following that doc https://hexdocs.pm/rollbax/using-rollbax-in-plug-based-applications.html 
so Rollbarx is reporting everything went to private function handle_errors

**Comment by noma4i** [comment]
as example https://github.com/rollbar/rollbar-gem which enables ignoring common non-exceptions like RoutingError, ActionNotFound

**Comment by whatyouhide** [comment]
Since you're manually reporting errors in `handle_errors/2`, you definitely can filter on whatever criteria you like.

```elixir
def handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
  if kind == :error and reason.exception == RoutingError do
    :not_reporting
  else
    Rollbax.report(...)
  end
end
```

(replace appropriate names and values of course)

**Comment by noma4i** [comment]
I can report errors just making request to rollbar api :) Question was: do
you plan to make white/black listing for errors.

-- 
Alex T

**Comment by whatyouhide** [comment]
Since you are already making requests to the Rollbax API (with `Rollbax.report/3-5` ) and **explicitly** reporting errors in your code, there is no reason for Rollbax to make a magic whitelist/blacklist of errors to report, you can very easily implement this as shown above. Not sure how you would have this in a more succinct way anywaws?

**Comment by whatyouhide** [comment]
@noma4i any news? I lean on closing this as I believe we can avoid complexity in the library and move such checks to user land, but I'm interested in understanding how you would want to use such white-blacklisting in the Rollbax API.

**Comment by oyvindfanebust** [comment]
Here is a use case from our code base: https://github.com/ninenines/cowboy/issues/1000

Cowboy logs invalid http calls as errors, but we get calls like these all the time (from crawlers perhaps?) and would like to avoid that they drown out our actual errors.

**Comment by whatyouhide** [comment]
@oyvindfanebust thanks for the use case, but I'm not sure we're on the same page.

I understand and share the use case of whitelisting a set of errors so that when they happen they do not get reported to Rollbar. However, I don't think Rollbax (this library) can do anything that will significantly improve today's state, where you can **implement this whitelisting in your own code** as I show in the code snippet above. Is there anything that prevents you from using something like the code above and/or do you have anything in mind that Rollbax could do to **significantly** make this easier?

**Comment by oyvindfanebust** [comment]
@whatyouhide The way I've set up Rollbax, I don't actually log errors manually, but Plug (I think) uses whatever logger is registered to log exceptions. There is no way to hook into the Plug framework to avoid this as far as I can see..

What I would propose is an optional config option to point to a function that determines whether or not to log the error.

**Comment by whatyouhide** [comment]
@oyvindfanebust the problem with that is that `Rollbax.Logger` only receives a *message* (chardata), not an inspectable exception. The only way I see filtering to work would be by providing a whitelisting regex, but I am really not a fan of this. 😕 Thoughts @lexmag?

**Comment by noma4i** [comment]
@whatyouhide finished with case with pattern match to throw route errors to nowhere

**Comment by oyvindfanebust** [comment]
Hey guys. Added a pull request for a whitelist feature. What do you think?

**Comment by whatyouhide** [comment]
Closing this in favor of #48. Feel free to ping here if you feel like this should be reopened! 👍
