### ISSUE TITLE
Are :info and :debug logs supported/working?

### ISSUE THREAD

**Issue by AdamBrodzinski** [elixir-addicts/rollbax#57]
I'm having issues getting the `Logger.info` and `Logger.debug` to log to Rollbar. I have my level set to `:info` but I can only log error to the service (the debug/info do log to the console though).

```
config :logger,
  backends: [:console, Rollbax.Logger],
  level: :debug  # also tried :info with no success

config :rollbax,
  access_token: System.get_env("ROLLBAR_TOKEN"),
  environment: Mix.env
```

**Comment by AdamBrodzinski** [comment]
Also are you open to PRs to add these? I'd rather do that than create a whole new Rollbar library. 

Semi related is providing support for a "custom" field which is a JSON serializable object that shows up in the reporting... typically in the JS version I would use things like user data if provided. This would be very helpful in the `:error/:ok` workflow where you don't want to throw an exception but still want to log an error with some metadata for debugging.

Thoughts?

**Comment by whatyouhide** [comment]
Hey @AdamBrodzinski, thanks for the issue. `:info` and `:debug` are indeed supported. `Rollbax.Logger` has to be configured with its specific level since it may not make sense to configure it with the same logging level as other Logger backends:

```elixir
# All the config you had, plus:
config :logger, Rollbax.Logger,
  level: :debug
```

As per the "custom" field, it is indeed supported in [`Rollbax.report/5`](https://hexdocs.pm/rollbax/0.8.1/Rollbax.html#report/5). If you're having problems with making that work, please open a separate issue and we can investigate further :D
