### ISSUE TITLE
Configuring :enabled from env variable

### ISSUE THREAD

**Issue by Zorbash** [elixir-addicts/rollbax#72]
I can see in the docs that rollbax allow configuring `:access_token` and `:environment` from env variables, but not :enabled. What is the rationale for this choice? Would you accept a PR changing this behaviour?

```
The `:access_token` and `:environment` options accept a binary or a
  `{:system, "VAR_NAME"}` tuple. When given a tuple like `{:system, "VAR_NAME"}`,
  the value will be referenced from `System.get_env("VAR_NAME")` at runtime.
```

**Comment by whatyouhide** [comment]
https://github.com/elixir-addicts/rollbax/pull/80 makes this invalid: you can now configure a `:config_callback` which can change the configuration at runtime, thus you can read values from the system environment, or a database, or wherever you want when Rollbax is started :).

This will be part of the next release, which should come in a few days, but I'll close the issue as the problem is not there anymore. Thanks @Zorbash! 💟
