### ISSUE TITLE
Should not require access_token when not enabled

### ISSUE THREAD

**Issue by jnicklas** [elixir-addicts/rollbax#9]
Currently rollbax refuses to start if an `access_token` and `environment` is not given even if it is not actually enabled. This is inconvenient if we want to add rollbax only in the production environment. It is possibly to specify an invalid token and get around this issue, but it feels like that shouldn't be necessary.

**Comment by lexmag** [comment]
I might agree that `access_token` shouldn't be required when `enabled` is set to `false`, but it feels consistent and more friendly to newcomers: they will get an error at early stage, not after production build is ready. I'm afraid that they will run recompilation to apply configuration changes since not everyone at the beginning knows about `sys.config` file.
